version: '3.4'

services:
  ecoflow:
    image: ecoflow-homie-bridge
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 venv/lib/python3.11/site-packages/pip/_internal/commands/index.py "]
    ports:
      - 5678:5678          
    environment:
      - EF_USERNAME=${EF_USERNAME}
      - EF_PASSWORD=${EF_PASSWORD}
      - HOMIE_MQTT=${HOMIE_MQTT}
      - HOMIE_MQTT_PORT=${HOMIE_MQTT_PORT}
    volumes:
      - "./logs:/var/log/ecoflow:z"
      - "./configs:/etc/ecoflow:z"
